### PR TITLE
Fix array length comparison

### LINKED ISSUE #444: Incorrect list length comparison
## :ghost: Brief Description

`FATAL: NoMethodError: undefined method '>' for ["eu", "central", "1b"]:Array`
I'm getting this error after upgrading to 9.0.1 version when I'm trying to use `aws_ssm_parameter_store` resource.
The problem is only reproducible in 9.0.1 version, with 9.0.0 works fine.
I think it's related to [commit](https://github.com/sous-chefs/aws/commit/83256886b6a95a03478f41cc8cbe66f38e8dd30c)
`split` function returns the list of string therefore `length` must be used, isn't it?
The line `if node['ec2']['placement_availability_zone'].split('-') > 3` should be `if node['ec2']['placement_availability_zone'].split('-').length() > 3`

## :pancakes: Cookbook version

9.0.1

## :woman_cook:  Chef-Infra Version

Tested with 16.16.13 and 17.7.29

## :tophat: Platform details

Tested only on Ubuntu, but most probably it's a common problem

## Steps To Reproduce

```ruby
aws_ssm_parameter_store "/test/path" do
  return_key 'value'
  with_decryption true
  action :get
end
```

### PR DESCRIPTION
**Pull request by bdwyertech**
# Description

Fixes broken array length comparison introduced in https://github.com/sous-chefs/aws/pull/443

https://github.com/sous-chefs/aws/blob/be61ac22d8fc2f69aa917b1815fd76b3283f3ab3/libraries/ec2.rb#L59

```
[2021-11-04T14:57:41+00:00] FATAL: NoMethodError: undefined method `>' for ["us", "east", "1b"]:Array
```

## Issues Resolved

#444 

## Check List

- [ ] A summary of changes made is included in the CHANGELOG under `## Unreleased`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by damacus — APPROVED** [review]

**Comment by damacus** [comment]
Can you add an entry to the CHANGELOG please and we'll get it shipped asap

**Comment by bdwyertech** [comment]
> Can you add an entry to the CHANGELOG please and we'll get it shipped asap

Done

**Review by hlopp — APPROVED** [review]

**Review by amoreno-gcm — APPROVED** [review]

**Review by damacus — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [9.0.2](https://github.com/sous-chefs/aws/releases/tag/9.0.2)
